apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 80           # Puerto externo al que se conecta
      targetPort: 5000    # Puerto al que se conecta el contenedor
  type: LoadBalancer      # Crea un Load Balancer en AWS
