name: Build and Deploy Docker Image to ECR ObligatorioDevOps

on:
  push:
    branches:
      - main  # O la rama que elijas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ASIA4RDAFRGRIK46CWM4 }}
          aws-secret-access-key: ${{ secrets.DDdbJ1+4FsQRzIbKYzGHDrNKAqDP3p5H5NO4JlOo }}
          aws-region: ${{ secrets.us-east-1 }}

      # Paso 3: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 4: Iniciar sesión en Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.us-east-1 }} | docker login --username matiaswsr@gmail.com --password-stdin ${{ secrets.861342632354 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com

      # Paso 5: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.861342632354 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com/my-repo-name:latest .

      # Paso 6: Subir la imagen a ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.861342632354 }}.dkr.ecr.${{ secrets.us-east-1 }}.amazonaws.com/my-repo-name:latest

